//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.MicroServices.LuckyDraw.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LuckyDrawServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LuckyDrawServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMS.MicroServices.LuckyDraw.Service.Resources.LuckyDrawServiceResource", typeof(LuckyDrawServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média Colegas.
        /// </summary>
        public static string CHART_COWORKERS_AVERAGE {
            get {
                return ResourceManager.GetString("CHART_COWORKERS_AVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliado como.
        /// </summary>
        public static string CHART_EVALUATED_AS {
            get {
                return ResourceManager.GetString("CHART_EVALUATED_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colega(s) Extra(s).
        /// </summary>
        public static string CHART_EXTRA_COWORKERS {
            get {
                return ResourceManager.GetString("CHART_EXTRA_COWORKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média Imediatos.
        /// </summary>
        public static string CHART_IMMEDIATE_LEADER_AVERAGE {
            get {
                return ResourceManager.GetString("CHART_IMMEDIATE_LEADER_AVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média Chefia.
        /// </summary>
        public static string CHART_LEADERSHIP_AVERAGE {
            get {
                return ResourceManager.GetString("CHART_LEADERSHIP_AVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média Mediatos.
        /// </summary>
        public static string CHART_MEDIATE_LEADER_AVERAGE {
            get {
                return ResourceManager.GetString("CHART_MEDIATE_LEADER_AVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média Total Imediatos.
        /// </summary>
        public static string CHART_OTHER_IMMEDIATE_LEADER_AVERAGE {
            get {
                return ResourceManager.GetString("CHART_OTHER_IMMEDIATE_LEADER_AVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média Total Mediados.
        /// </summary>
        public static string CHART_OTHER_MEDIATE_LEADER_AVERAGE {
            get {
                return ResourceManager.GetString("CHART_OTHER_MEDIATE_LEADER_AVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração {0} carregada do Consul em {1}..
        /// </summary>
        public static string CONSUL_CONFIGURATION_LOADED {
            get {
                return ResourceManager.GetString("CONSUL_CONFIGURATION_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem avaliação.
        /// </summary>
        public static string NO_EVALUATION {
            get {
                return ResourceManager.GetString("NO_EVALUATION", resourceCulture);
            }
        }
    }
}
