//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.MicroServices.LuckyDraw.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LuckyDrawDomainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LuckyDrawDomainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMS.MicroServices.LuckyDraw.Domain.Resources.LuckyDrawDomainResource", typeof(LuckyDrawDomainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concordo.
        /// </summary>
        public static string AGREEMENT_ENUM_AGREE {
            get {
                return ResourceManager.GetString("AGREEMENT_ENUM_AGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discordo.
        /// </summary>
        public static string AGREEMENT_ENUM_DISAGREE {
            get {
                return ResourceManager.GetString("AGREEMENT_ENUM_DISAGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutro.
        /// </summary>
        public static string AGREEMENT_ENUM_NEUTRAL {
            get {
                return ResourceManager.GetString("AGREEMENT_ENUM_NEUTRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem avaliação.
        /// </summary>
        public static string AGREEMENT_ENUM_NOT_SET {
            get {
                return ResourceManager.GetString("AGREEMENT_ENUM_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concordo parcialmente.
        /// </summary>
        public static string AGREEMENT_ENUM_PARTIALLY_AGREE {
            get {
                return ResourceManager.GetString("AGREEMENT_ENUM_PARTIALLY_AGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discordo parcialmente.
        /// </summary>
        public static string AGREEMENT_ENUM_PARTIALLY_DISAGREE {
            get {
                return ResourceManager.GetString("AGREEMENT_ENUM_PARTIALLY_DISAGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concordo totalmente.
        /// </summary>
        public static string AGREEMENT_ENUM_TOTALLY_AGREE {
            get {
                return ResourceManager.GetString("AGREEMENT_ENUM_TOTALLY_AGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discordo totalmente.
        /// </summary>
        public static string AGREEMENT_ENUM_TOTALLY_DISAGREE {
            get {
                return ResourceManager.GetString("AGREEMENT_ENUM_TOTALLY_DISAGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem avaliação.
        /// </summary>
        public static string NO_EVALUATION {
            get {
                return ResourceManager.GetString("NO_EVALUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insatisfeito.
        /// </summary>
        public static string SATISFACTION_ENUM_DISSATISFIED {
            get {
                return ResourceManager.GetString("SATISFACTION_ENUM_DISSATISFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutro.
        /// </summary>
        public static string SATISFACTION_ENUM_NEUTRAL {
            get {
                return ResourceManager.GetString("SATISFACTION_ENUM_NEUTRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem avaliação.
        /// </summary>
        public static string SATISFACTION_ENUM_NOT_SET {
            get {
                return ResourceManager.GetString("SATISFACTION_ENUM_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcialmente insatisfeito.
        /// </summary>
        public static string SATISFACTION_ENUM_PARTIALLY_DISSATISFIED {
            get {
                return ResourceManager.GetString("SATISFACTION_ENUM_PARTIALLY_DISSATISFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcialmente satisfeito.
        /// </summary>
        public static string SATISFACTION_ENUM_PARTIALLY_SATISFIED {
            get {
                return ResourceManager.GetString("SATISFACTION_ENUM_PARTIALLY_SATISFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfeito.
        /// </summary>
        public static string SATISFACTION_ENUM_SATISFIED {
            get {
                return ResourceManager.GetString("SATISFACTION_ENUM_SATISFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muito insatisfeito.
        /// </summary>
        public static string SATISFACTION_ENUM_VERY_DISSATISFIED {
            get {
                return ResourceManager.GetString("SATISFACTION_ENUM_VERY_DISSATISFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muito satisfeito.
        /// </summary>
        public static string SATISFACTION_ENUM_VERY_SATISFIED {
            get {
                return ResourceManager.GetString("SATISFACTION_ENUM_VERY_SATISFIED", resourceCulture);
            }
        }
    }
}
